apps/config/routes.rb
Rails.application.routes.draw do
  resources :regulations
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :calendars
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "rooms#index"
end

apps/app/views/layouts/_navi.html.erb
<nav class="bg-purple-900 text-white flex justify-between">
  <img src="" alt="" class="h-14 rounded-full px-0">
  <ul class="px-10 py-4 flex space-x-3">
    <%= content_tag(:li, class: "cursor-pointer") do
      link_to("HOME", root_path) end if !admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
      link_to("ルーム", rooms_path) end if admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
      link_to("就業規則", regulations_path) end if admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
      link_to("カレンダー", calendars_path) end if admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
      link_to("登録", new_user_registration_path) end  if !user_signed_in? && !admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
      link_to("ログイン", new_user_session_path) end if !user_signed_in? && !admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
      link_to("ADMINログイン", new_admin_session_path) end if !user_signed_in? && !admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
      link_to("ログアウト", destroy_user_session_path, data:{ turbo_method: :delete }) end if user_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
      link_to("ADMINログアウト", destroy_user_session_path, data:{ turbo_method: :delete }) end if admin_signed_in? %>

    <%= content_tag(:li, class: "cursor-pointer") do
      link_to("ADMIN登録", new_admin_registration_path) end if !user_signed_in? && !admin_signed_in? %>
  </ul>
</nav>

apps/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navi' %>
    <div class="container mt-6 px-3">
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="alert"><%= alert %></p>
      <% end %>
    </div>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>