apps/config/routes.rb
Rails.application.routes.draw do
  resources :regulations
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :calendars
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "rooms#index"
end

apps/app/models/room.rb
class Room < ApplicationRecord
end

apps/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_path, status: :see_other, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :profile)
    end
end

apps/app/helpers/rooms_helper.rb
module RoomsHelper
end

apps/app/views/rooms/_form.html.erb
<%= form_with(model: room, class: "contents") do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul class="list-disc ml-6">
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": room.errors[:name].none?, "border-red-400 focus:outline-red-600": room.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :profile %>
    <%= form.text_area :profile, rows: 4, class: ["block shadow rounded-md border outline-none px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": room.errors[:profile].none?, "border-red-400 focus:outline-red-600": room.errors[:profile].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

apps/app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">ルーム名:</strong>
    <%= room.name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">詳細案内:</strong>
    <%= room.profile %>
  </p>
</div>

apps/app/views/rooms/edit.html.erb
<% content_for :title, "Editing room" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing room</h1>

  <%= render "form", room: @room %>

  <%= link_to "詳細", @room, class: "link_btn_ml2" %>
  <%= link_to "戻る", rooms_path, class: "link_btn_ml2" %>
</div>

apps/app/views/rooms/index.html.erb
<% content_for :title, "Rooms" %>

<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">ルーム一覧</h1>
    <%= link_to"新規ルーム作成", new_room_path, class:"new_btn" if admin_signed_in? %>
  </div>

  <div id="rooms" class="min-w-full">
    <% if @rooms.any? %>
      <% @rooms.each do |room| %>
        <%= render room %>
        <p>
          <%= link_to "表示", room, class: "link_btn" %>
          <%= link_to "編集", edit_room_path(room), class: "link_btn_mt2" if admin_signed_in? %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10">No rooms found.</p>
    <% end %>
  </div>
</div>

apps/app/views/rooms/new.html.erb
<% content_for :title, "New room" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">新規ルーム</h1>

  <%= render "form", room: @room %>

  <%= link_to "Back to rooms", rooms_path, class: "link_btn_ml2" %>
</div>

apps/app/views/rooms/show.html.erb
<% content_for :title, "Showing room" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">ルーム詳細</h1>

  <%= render @room %>

  <%= link_to "編集", edit_room_path(@room), class: "link_btn_mt2" if admin_signed_in? %>
  <%= link_to "戻る", rooms_path, class: "link_btn_ml2" %>
  <div class="inline-block ml-2">
    <%= button_to "削除", @room, method: :delete, class: "delete_btn" if admin_signed_in? %>
  </div>
</div>