apps/config/routes.rb
Rails.application.routes.draw do
  resources :regulations
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
    sessions: 'admins/sessions'
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :calendars
  resources :rooms
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "rooms#index"
end

apps/app/models/regulation.rb
class Regulation < ApplicationRecord
end

apps/app/controllers/regulations_controller.rb
class RegulationsController < ApplicationController
  before_action :set_regulation, only: %i[ show edit update destroy ]

  # GET /regulations or /regulations.json
  def index
    @regulation = Regulation.last
  end

  # GET /regulations/1 or /regulations/1.json
  def show
  end

  # GET /regulations/new
  def new
    @regulation = Regulation.new
  end

  # GET /regulations/1/edit
  def edit
  end

  # POST /regulations or /regulations.json
  def create
    @regulation = Regulation.new(regulation_params)

    respond_to do |format|
      if @regulation.save
        format.html { redirect_to @regulation, notice: "Regulation was successfully created." }
        format.json { render :show, status: :created, location: @regulation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @regulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regulations/1 or /regulations/1.json
  def update
    respond_to do |format|
      if @regulation.update(regulation_params)
        format.html { redirect_to @regulation, notice: "Regulation was successfully updated." }
        format.json { render :show, status: :ok, location: @regulation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @regulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regulations/1 or /regulations/1.json
  def destroy
    @regulation.destroy!

    respond_to do |format|
      format.html { redirect_to regulations_path, status: :see_other, notice: "Regulation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regulation
      @regulation = Regulation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def regulation_params
      params.require(:regulation).permit(:begin_time, :close_time, :interval_s, :interval_e, :unit_minute, :versions)
    end
end

apps/app/helpers/regulations_helper.rb
module RegulationsHelper
end

apps/app/views/regulations/_form.html.erb
<%= form_with(model: regulation, class: "contents") do |form| %>
  <% if regulation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(regulation.errors.count, "error") %> prohibited this regulation from being saved:</h2>

      <ul class="list-disc ml-6">
        <% regulation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :begin_time %>
    <%= form.select :begin_time, ["08:00", "08:30", "09:00", "09:30", "10:00" ], {selected: "09:00"},
        class: "frm_ln" %>
  </div>

  <div class="my-5">
    <%= form.label :close_time %>
    <%= form.select :close_time, ["16:00", "16:30", "17:00", "17:30", "18:00" ], {selected: "17:00"},
        class: "frm_ln" %>
  </div>

  <div class="my-5">
    <%= form.label :interval_s %>
    <%= form.select :interval_s, ["11:00", "11:30", "12:00", "12:30", "13:00" ], {selected: "12:00"},
        class: "frm_ln" %>
  </div>

  <div class="my-5">
    <%= form.label :interval_e %>
    <%= form.select :interval_e, ["12:00", "12:30", "13:00", "13:30", "14:00" ], {selected: "13:00"},
        class: "frm_ln" %>
  </div>

  <div class="my-5">
    <%= form.label :unit_minute %>
    <%= form.select :unit_minute, [15, 30, 60], {selected: 30},
        class: "frm_ln" %>
  </div>

  <div class="my-5">
    <%= form.label :version %>
    <%= form.text_field :version, class: "frm_ln" %>
  </div>

  <div class="inline">
    <%= form.submit class: "frm_btn bg-blue-600" %>
  </div>
<% end %>

apps/app/views/regulations/_regulation.html.erb
<div id="<%= dom_id regulation %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">開始時刻:</strong>
    <%= regulation.begin_time %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">終了時刻:</strong>
    <%= regulation.close_time %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">昼休開始:</strong>
    <%= regulation.interval_s %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">昼休終了:</strong>
    <%= regulation.interval_e %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">単位：分:</strong>
    <%= regulation.unit_minute %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">バージョン:</strong>
    <%= regulation.versions %>
  </p>
</div>

apps/app/views/regulations/edit.html.erb
<% content_for :title, "Editing regulation" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">編集 就業規則</h1>

  <%= render "form", regulation: @regulation %>

  <%= link_to "詳細", @regulation, class: "link_btn_ml2" %>
  <%= link_to "戻る", regulations_path, class: "link_btn_ml2" %>
</div>

apps/app/views/regulations/index.html.erb
<% content_for :title, "Regulations" %>

<div class="w-full">
  <table class="table-auto">
    <caption class="text-2xl font-bold pb-4">就業規則</caption>
    <thead>
      <tr>
        <th class="px-4 py-2">始業時刻</th>
        <th class="px-4 py-2">終業時刻</th>
        <th class="px-4 py-2">昼休開始</th>
        <th class="px-4 py-2">昼休終了</th>
        <th class="px-4 py-2">単位：分</th>
        <th class="px-4 py-2">バージョン</th>
        <th class="px-4 py-2"></th>
        <th class="px-4 py-2"></th>
        <th class="px-4 py-2"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="border px-4 py-2"><%= @regulation.begin_time if @regulation %></td>
        <td class="border px-4 py-2"><%= @regulation.close_time if @regulation %></td>
        <td class="border px-4 py-2"><%= @regulation.interval_s if @regulation %></td>
        <td class="border px-4 py-2"><%= @regulation.interval_e if @regulation %></td>
        <td class="border px-4 py-2"><%= @regulation.unit_minute if @regulation %></td>
        <td class="border px-4 py-2"><%= @regulation.versions if @regulation %></td>
        <td class="border px-4 py-2"><%= link_to '新規作成', new_regulation_path, class:"frm_btn bg-blue-400" if @regulation %></td>
        <td class="border px-4 py-2"><%= link_to '変更', edit_regulation_path(@regulation), method: :delete, class:"frm_btn bg-green-400" if @regulation %></td>
      </tr>
    </tbody>
  </table>
</div>

apps/app/views/regulations/new.html.erb
<% content_for :title, "New regulation" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">新規 終業規則</h1>

  <%= render "form", regulation: @regulation %>

  <%= link_to "戻る", regulations_path, class: "link_btn_ml2" %>
</div>

apps/app/views/regulations/show.html.erb
<% content_for :title, "Showing regulation" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">就業規則 詳細</h1>

  <%= render @regulation %>

  <%= link_to "編集", edit_regulation_path(@regulation), class: "link_btn_mt2" %>
  <%= link_to "戻る", regulations_path, class: "link_btn_ml2" %>
  <div class="inline-block ml-2">
    <%= button_to "削除", @regulation, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
  </div>
</div>